### ISSUE TITLE
[FeatureREQ] Change internal solid infill pattern

### ISSUE THREAD

**Issue by Hammerfest** [ANYCUBIC-3D/AnycubicSlicer#8]
Unable to print clear filament for clear parts, cannot set internal solid infill pattern to match top and bottom.
Can easily do it in other slicers.

If its possible please change the labeling to accommodate.

**Comment by wydowaw** [comment]
[FeatureREQ]  file naming.
I would like to add the mass to the file name as a paramater.
Must be possible, total_time is in it now...so mass coould be a feature to switch on
